### PR TITLE
Adds support for TinyMCE 4.x.x (Removes support from 3.x.x)

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
- Pull upstream (nytimes) master
- Remove TinyMCE 3.5 related code
- Changed folder structure of plugins to match that of TinyMCE 4.x.x

Only thing left (to my knowledge)
- When building, the plugin files are named plugin.js instead of plugin.min.js (any help on that would be awesome)

### CODE REVIEW

**Comment by itmilos** [comment]
@NullVoxPopuli is this plugin tested on 4.3.x ?

**Comment by NullVoxPopuli** [comment]
@itmilos, I'm not sure. @jheth might be able to answer though?

**Comment by jheth** [comment]
@itmilos We are on 4.3.6 and continue to use this plugin.  We have had to make slight tweaks to it over time but it has held up really well.

**Comment by NullVoxPopuli** [comment]
Cleaning up my PRs. If this work is still desired, feel free to cherry-pick

**Pull request closed without merging**
